# Generated by Django 4.2.20 on 2025-04-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('track_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='recommender.song')),
                ('source_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='recommender.song')),
            ],
            options={
                'ordering': ['-similarity_score'],
                'unique_together': {('source_song', 'recommended_song')},
            },
        ),
    ]
